package dbs.corba.FailureFreeFEPackage;


/**
* dbs/corba/FailureFreeFEPackage/reultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Sunday, December 3, 2017 12:34:16 PM EST
*/

public final class reultHolder implements org.omg.CORBA.portable.Streamable
{
  public dbs.corba.clientList value[] = null;

  public reultHolder ()
  {
  }

  public reultHolder (dbs.corba.clientList[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dbs.corba.FailureFreeFEPackage.reultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dbs.corba.FailureFreeFEPackage.reultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dbs.corba.FailureFreeFEPackage.reultHelper.type ();
  }

}
