package dbs.corba;

/**
* dbs/corba/CallBackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Friday, December 1, 2017 10:26:46 PM EST
*/

public final class CallBackHolder implements org.omg.CORBA.portable.Streamable
{
  public dbs.corba.CallBack value = null;

  public CallBackHolder ()
  {
  }

  public CallBackHolder (dbs.corba.CallBack initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dbs.corba.CallBackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dbs.corba.CallBackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dbs.corba.CallBackHelper.type ();
  }

}
