package dbs.corba;


/**
* dbs/corba/CallBackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Friday, December 1, 2017 10:26:46 PM EST
*/

public interface CallBackOperations 
{
  void responseMessage (String message);
} // interface CallBackOperations
