package dbs.corba;


/**
* dbs/corba/CallBackHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Sunday, December 3, 2017 12:34:16 PM EST
*/

abstract public class CallBackHelper
{
  private static String  _id = "IDL:dbs/corba/CallBack:1.0";

  public static void insert (org.omg.CORBA.Any a, dbs.corba.CallBack that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dbs.corba.CallBack extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (dbs.corba.CallBackHelper.id (), "CallBack");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dbs.corba.CallBack read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CallBackStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dbs.corba.CallBack value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static dbs.corba.CallBack narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dbs.corba.CallBack)
      return (dbs.corba.CallBack)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dbs.corba._CallBackStub stub = new dbs.corba._CallBackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static dbs.corba.CallBack unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dbs.corba.CallBack)
      return (dbs.corba.CallBack)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dbs.corba._CallBackStub stub = new dbs.corba._CallBackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
