package dbs.corba;


/**
* dbs/corba/CallBackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Sunday, December 3, 2017 12:34:16 PM EST
*/

public interface CallBackOperations 
{
  void responseMessage (String message);
} // interface CallBackOperations
