package dbs.corba;

/**
* dbs/corba/clientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Sunday, December 3, 2017 12:34:16 PM EST
*/

public final class clientHolder implements org.omg.CORBA.portable.Streamable
{
  public dbs.corba.client value = null;

  public clientHolder ()
  {
  }

  public clientHolder (dbs.corba.client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dbs.corba.clientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dbs.corba.clientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dbs.corba.clientHelper.type ();
  }

}
