package dbs.corba;


/**
* dbs/corba/client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Friday, December 1, 2017 10:26:46 PM EST
*/

public final class client implements org.omg.CORBA.portable.IDLEntity
{
  public String firstName = null;
  public String lastName = null;
  public String address = null;
  public String phoneNum = null;
  public String clientID = null;

  public client ()
  {
  } // ctor

  public client (String _firstName, String _lastName, String _address, String _phoneNum, String _clientID)
  {
    firstName = _firstName;
    lastName = _lastName;
    address = _address;
    phoneNum = _phoneNum;
    clientID = _clientID;
  } // ctor

} // class client
