package dbs.corba;


/**
* dbs/corba/FailureFreeFEOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Sunday, November 26, 2017 10:13:53 PM EST
*/

public interface FailureFreeFEOperations 
{
  String sayHello ();
  double deposit (long accountNum, float amount);
  double withdraw (long accountNum, float amount);
  double balance (long accountNum);
  double transfer (long src_accountNum, long dest_accountNum, float amount);
  String requestResponse (dbs.corba.CallBack cb);
  void shutdown ();
} // interface FailureFreeFEOperations
