package dbs.corba;


/**
* dbs/corba/FailureFreeFEOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Sunday, December 3, 2017 12:34:16 PM EST
*/

public interface FailureFreeFEOperations 
{
  String sayHello ();
  boolean deposit (String accountNum, float amount);
  boolean withdraw (String accountNum, float amount);
  float balance (String accountNum);
  boolean transfer (String src_accountNum, String dest_accountNum, float amount);
  String requestResponse (dbs.corba.CallBack cb);
  void shutdown ();
  boolean createAccount (String firstName, String lastName, String address, String phone, String customerID, String branchID);

  //result getAccountCount();
  int getLocalAccountCount ();

  //True if we want to set a replic to artificially produce a wrong result.
  void setByzantineFlag (boolean flag);
} // interface FailureFreeFEOperations
