package dbs.corba;


/**
* dbs/corba/FailureFreeFEHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Sunday, November 26, 2017 10:13:53 PM EST
*/

abstract public class FailureFreeFEHelper
{
  private static String  _id = "IDL:dbs/corba/FailureFreeFE:1.0";

  public static void insert (org.omg.CORBA.Any a, dbs.corba.FailureFreeFE that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dbs.corba.FailureFreeFE extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (dbs.corba.FailureFreeFEHelper.id (), "FailureFreeFE");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dbs.corba.FailureFreeFE read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FailureFreeFEStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dbs.corba.FailureFreeFE value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static dbs.corba.FailureFreeFE narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dbs.corba.FailureFreeFE)
      return (dbs.corba.FailureFreeFE)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dbs.corba._FailureFreeFEStub stub = new dbs.corba._FailureFreeFEStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static dbs.corba.FailureFreeFE unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dbs.corba.FailureFreeFE)
      return (dbs.corba.FailureFreeFE)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dbs.corba._FailureFreeFEStub stub = new dbs.corba._FailureFreeFEStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
