package dbs.corba;

/**
* dbs/corba/FailureFreeFEHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Sunday, December 3, 2017 12:34:16 PM EST
*/

public final class FailureFreeFEHolder implements org.omg.CORBA.portable.Streamable
{
  public dbs.corba.FailureFreeFE value = null;

  public FailureFreeFEHolder ()
  {
  }

  public FailureFreeFEHolder (dbs.corba.FailureFreeFE initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dbs.corba.FailureFreeFEHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dbs.corba.FailureFreeFEHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dbs.corba.FailureFreeFEHelper.type ();
  }

}
