package dbs.corba;


/**
* dbs/corba/FailureFreeFE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Sunday, November 26, 2017 10:13:53 PM EST
*/

public interface FailureFreeFE extends FailureFreeFEOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FailureFreeFE
