package dbs.corba;


/**
* dbs/corba/FailureFreeFEOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbs.idl
* Friday, December 1, 2017 10:26:46 PM EST
*/

public interface FailureFreeFEOperations 
{
  String sayHello ();
  double deposit (long accountNum, float amount);
  double withdraw (long accountNum, float amount);
  double balance (long accountNum);
  double transfer (long src_accountNum, long dest_accountNum, float amount);
  String requestResponse (dbs.corba.CallBack cb);
  void shutdown ();
  boolean createAccount (String firstName, String lastName, String address, String phone, String customerID, String branchID);

  //True if we want to set a replic to artificially produce a wrong result.
  void setByzantineFlag (boolean flag);
} // interface FailureFreeFEOperations
