package common.BankServerInterfacePackage;


/**
* common/BankServerInterfacePackage/accountsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Thursday, November 2, 2017 4:02:20 PM EDT
*/

public final class accountsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public accountsHolder ()
  {
  }

  public accountsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.BankServerInterfacePackage.accountsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.BankServerInterfacePackage.accountsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.BankServerInterfacePackage.accountsHelper.type ();
  }

}
