//To start, go to "src" folder and use command "idlj -fall dbs.idl".
module dbs
{
	module corba
	{
		struct client
		{
			string firstName;
			string lastName;
			string address;
			string phoneNum;
			string clientID;
		};
		
		struct clientList
		{
			string branchID;
			sequence<client> allClients;
		};
		
		interface CallBack
		{
			void responseMessage(in string message);
		};
		
		interface FailureFreeFE
		{
			typedef sequence<clientList> reult;
			
			string sayHello();
			boolean deposit(in string accountNum,in float amount);
			boolean withdraw(in string accountNum,in float amount);
			float balance(in string accountNum);
			boolean transfer(in string src_accountNum,in string dest_accountNum,in float amount);
			
			string requestResponse(in CallBack cb);
			
			oneway void shutdown();
			
			boolean createAccount(in string firstName, in string lastName, in string address, in string phone, in string customerID, in string branchID);
			
			//result getAccountCount();
			long getLocalAccountCount();
			
			//True if we want to set a replic to artificially produce a wrong result.
			void setByzantineFlag(in boolean flag);
		};
	};
};