package common;


/**
* common/BankServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Thursday, November 2, 2017 4:02:20 PM EDT
*/


//Interface for the Banking Server
public interface BankServerInterfaceOperations 
{
  int getLocalAccountCount ();
  String[] getAllCustomerAccount ();
  boolean createAccount (String firstName, String lastName, String address, String phone, String customerID, common.BranchID branchID) throws common.BankServerInterfacePackage.invalid_client;
  boolean editRecord (String customerID, common.EditRecordFields fieldName, String newValue) throws common.BankServerInterfacePackage.invalid_client;
  boolean deposit (String customerID, double amount) throws common.BankServerInterfacePackage.invalid_client, common.BankServerInterfacePackage.invalid_bankOperation;
  boolean withdraw (String customerID, double amount) throws common.BankServerInterfacePackage.invalid_client, common.BankServerInterfacePackage.invalid_bankOperation;
  double getBalance (String customerID) throws common.BankServerInterfacePackage.invalid_client;
  boolean transferFund (String sourceID, float amount, String destID) throws common.BankServerInterfacePackage.invalid_client, common.BankServerInterfacePackage.invalid_bankOperation;
  int getUDPPort ();
  String getUDPHost ();
  void shutdown ();
} // interface BankServerInterfaceOperations
