package common;


/**
* common/BranchID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Thursday, November 2, 2017 4:02:20 PM EDT
*/

public class BranchID implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static common.BranchID[] __array = new common.BranchID [__size];

  public static final int _BC = 0;
  public static final common.BranchID BC = new common.BranchID(_BC);
  public static final int _MB = 1;
  public static final common.BranchID MB = new common.BranchID(_MB);
  public static final int _NB = 2;
  public static final common.BranchID NB = new common.BranchID(_NB);
  public static final int _QC = 3;
  public static final common.BranchID QC = new common.BranchID(_QC);

  public int value ()
  {
    return __value;
  }

  public static common.BranchID from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected BranchID (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class BranchID
