package common;

/**
* common/EditRecordFieldsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bankserver.idl
* Thursday, November 2, 2017 4:02:20 PM EDT
*/

public final class EditRecordFieldsHolder implements org.omg.CORBA.portable.Streamable
{
  public common.EditRecordFields value = null;

  public EditRecordFieldsHolder ()
  {
  }

  public EditRecordFieldsHolder (common.EditRecordFields initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.EditRecordFieldsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.EditRecordFieldsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.EditRecordFieldsHelper.type ();
  }

}
